# Generated by Django 2.1.2 on 2018-10-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.CharField(default='هانی', max_length=50),
        ),
    ]
