# Generated by Django 2.1.2 on 2018-10-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='city',
            field=models.CharField(default='تهران', max_length=50),
        ),
    ]
