# Generated by Django 2.1.2 on 2018-10-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_food_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='foods/'),
        ),
    ]
