# Generated by Django 2.1.2 on 2018-10-06 18:51

from django.db import migrations, models
import foods.models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=foods.models.upload_image_path),
        ),
    ]
